# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180112_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='age',
            field=models.IntegerField(default='18', max_length=3, verbose_name='年龄'),
        ),
    ]
