# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180112_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
