# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180112_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
    ]
