# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_remove_usercourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
    ]
