# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_org', to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
